language: c

env:
  global:
    - LUAROCKS=2.2.0
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit

branches:
  only:
    - master

before_install:
  - bash .travis/setup_lua.sh

install:
  - sudo luarocks make rockspecs/lbase64-scm-0.rockspec

script:
  - lua test.lua

notifications:
  email:
    on_success: change
    on_failure: always
